version: "3.9"
services:
    app:
        container_name: varfrog-deadlock-app
        build: .
        volumes:
            - .:/usr/src/app
        depends_on:
            - db
    db:
        container_name: varfrog-deadlock-db
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: pass
